[package]
name = "crud"
version = "0.1.0"
authors = ["Dylan Fontana <dyfontana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "1.0.0"
tokio = "0.2.22"
futures = "0.3.5"
